# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./zfs.nix
    ./nfs.nix
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "megaraid_sas"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # # nfs
  # boot.supportedFilesystems = [ "nfs" ];
  # services.rpcbind.enable = true; # needed for NFS
  #
  # fileSystems = {
  #   "/mnt/NAS/appdata" = {
  #     device = "truenas.local:/mnt/NAS/appdata/mikoto";
  #     fsType = "nfs";
  #   };
  #   "/mnt/NAS/docker-storage" = {
  #     device = "truenas.local:/mnt/NAS/docker-storage";
  #     fsType = "nfs";
  #   };
  #   "/mnt/NAS/share" = {
  #     device = "truenas.local:/mnt/NAS/share";
  #     fsType = "nfs";
  #   };
  # };
  #
  # systemd.services.docker = {
  #   # 'requires' 表示强依赖：如果挂载失败，Docker 不会启动
  #   requires = [
  #     "mnt-NAS-appdata.mount"
  #     "mnt-NAS-docker\\x2dstorage.mount"
  #     "mnt-NAS-share.mount"
  #   ];
  # };

  swapDevices = [ { device = "/dev/zvol/rpool/swap"; } ];

  #显卡
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = false; # V100 不需要
    open = false; # V100 是 Volta，不支持 open driver
    nvidiaSettings = false;
    package = config.boot.kernelPackages.nvidiaPackages.legacy_580; # 580 是支持 V100 的最后一个版本
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
